swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /metodologia/:
    get:
      tags:
      - metodologia
      description: get Metodologia
      operationId: MetodologiaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Metodologia'
        "404":
          description: not found resource
    post:
      tags:
      - metodologia
      description: create Metodologia
      operationId: MetodologiaController.Post
      parameters:
      - in: body
        name: body
        description: body for Metodologia content
        required: true
        schema:
          $ref: '#/definitions/models.Metodologia'
      responses:
        "201":
          description: '{int} models.Metodologia'
        "400":
          description: the request contains incorrect syntax
  /metodologia/{id}:
    get:
      tags:
      - metodologia
      description: get Metodologia by id
      operationId: MetodologiaController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Metodologia'
        "403":
          description: :id is empty
    put:
      tags:
      - metodologia
      description: update the Metodologia
      operationId: MetodologiaController.Update
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Metodologia content
        required: true
        schema:
          $ref: '#/definitions/models.Metodologia'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Metodologia'
        "403":
          description: :id is not int
    delete:
      tags:
      - metodologia
      description: delete the Metodologia
      operationId: MetodologiaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /nivel_formacion/:
    get:
      tags:
      - nivel_formacion
      description: get NivelFormacion
      operationId: NivelFormacionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.NivelFormacion'
        "404":
          description: not found resource
    post:
      tags:
      - nivel_formacion
      description: create NivelFormacion
      operationId: NivelFormacionController.Post
      parameters:
      - in: body
        name: body
        description: body for NivelFormacion content
        required: true
        schema:
          $ref: '#/definitions/models.NivelFormacion'
      responses:
        "201":
          description: '{int} models.NivelFormacion'
        "400":
          description: the request contains incorrect syntax
  /nivel_formacion/{id}:
    get:
      tags:
      - nivel_formacion
      description: get NivelFormacion by id
      operationId: NivelFormacionController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.NivelFormacion'
        "403":
          description: :id is empty
    put:
      tags:
      - nivel_formacion
      description: update the NivelFormacion
      operationId: NivelFormacionController.Update
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for NivelFormacion content
        required: true
        schema:
          $ref: '#/definitions/models.NivelFormacion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.NivelFormacion'
        "403":
          description: :id is not int
    delete:
      tags:
      - nivel_formacion
      description: delete the NivelFormacion
      operationId: NivelFormacionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /programa_academico/:
    get:
      tags:
      - programa_academico
      description: get ProgramaAcademico
      operationId: ProgramaAcademicoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProgramaAcademico'
        "404":
          description: not found resource
    post:
      tags:
      - programa_academico
      description: create ProgramaAcademico
      operationId: ProgramaAcademicoController.Post
      parameters:
      - in: body
        name: body
        description: body for ProgramaAcademico content
        required: true
        schema:
          $ref: '#/definitions/models.ProgramaAcademico'
      responses:
        "201":
          description: '{int} models.ProgramaAcademico'
        "400":
          description: the request contains incorrect syntax
  /programa_academico/{id}:
    get:
      tags:
      - programa_academico
      description: get ProgramaAcademico by id
      operationId: ProgramaAcademicoController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProgramaAcademico'
        "403":
          description: :id is empty
    put:
      tags:
      - programa_academico
      description: update the ProgramaAcademico
      operationId: ProgramaAcademicoController.Update
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ProgramaAcademico content
        required: true
        schema:
          $ref: '#/definitions/models.ProgramaAcademico'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ProgramaAcademico'
        "403":
          description: :id is not int
    delete:
      tags:
      - programa_academico
      description: delete the ProgramaAcademico
      operationId: ProgramaAcademicoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /titulacion/:
    get:
      tags:
      - titulacion
      description: get Titulacion
      operationId: TitulacionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Titulacion'
        "404":
          description: not found resource
    post:
      tags:
      - titulacion
      description: create Titulacion
      operationId: TitulacionController.Post
      parameters:
      - in: body
        name: body
        description: body for Titulacion content
        required: true
        schema:
          $ref: '#/definitions/models.Titulacion'
      responses:
        "201":
          description: '{int} models.Titulacion'
        "400":
          description: the request contains incorrect syntax
  /titulacion/{id}:
    get:
      tags:
      - titulacion
      description: get Titulacion by id
      operationId: TitulacionController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Titulacion'
        "403":
          description: :id is empty
    put:
      tags:
      - titulacion
      description: update the Titulacion
      operationId: TitulacionController.Update
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Titulacion content
        required: true
        schema:
          $ref: '#/definitions/models.Titulacion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Titulacion'
        "403":
          description: :id is not int
    delete:
      tags:
      - titulacion
      description: delete the Titulacion
      operationId: TitulacionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
definitions:
  models.Metodologia:
    title: Metodologia
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.NivelFormacion:
    title: NivelFormacion
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.ProgramaAcademico:
    title: ProgramaAcademico
    type: object
    properties:
      Codigo:
        type: integer
        format: int64
      Duracion:
        type: number
        format: double
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Institucion:
        type: integer
        format: int64
      Metodologia:
        $ref: '#/definitions/models.Metodologia'
      NivelFormacion:
        $ref: '#/definitions/models.NivelFormacion'
      Nombre:
        type: string
      NucleoBasicoConocimiento:
        type: integer
        format: int64
      Titulacion:
        $ref: '#/definitions/models.Titulacion'
      UnidadTiempo:
        type: integer
        format: int64
  models.Titulacion:
    title: Titulacion
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaModificacion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: metodologia
  description: |
    oprations for Metodologia
- name: nivel_formacion
  description: |
    oprations for NivelFormacion
- name: titulacion
  description: |
    oprations for Titulacion
- name: programa_academico
  description: |
    oprations for ProgramaAcademico
